spin_manifest_version = 2

[application]
name = "spin-grpc-client"
version = "0.1.0"
authors = ["Brian Hardock <brian.hardock@fermyon.com>"]
description = "An example of using a gRPC client in Spin"

[[trigger.http]]
route = "/..."
component = "spin-grpc-client"

[component.spin-grpc-client]
source = "target/wasm32-wasip1/release/routeguide_client.wasm"
allowed_outbound_hosts = ["*://*:*"]
[component.spin-grpc-client.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
